### ISSUE TITLE
[D1.5] Boilerplate - Documentation

### ISSUE THREAD

**Issue by benjaminsalon** [paltalabs/create-soroban-dapp#1]
As the main focus of this boilerplate is to allow for better adoption of soroban smart contracts and front end deployment, we want here to provide a clear and extensive documentation to future users.

**Comment by esteblock** [comment]
- [ ] Create docs folder
- [ ] Connect with https://www.gitbook.com/
- [ ] Link with domain

**Comment by esteblock** [comment]
@benjaminsalon Let's work on this
