### ISSUE TITLE
Documentation Improvement and Fix for Soroban DApp Setup

### ISSUE THREAD

**Issue by chopan123** [paltalabs/create-soroban-dapp#14]
## ODHack
This issue is part of ODHack:

- [Description](https://app.onlydust.com/p/get-your-soroban-journey-started-with-create-soroban-dapp)
- [Guidelines](https://onlydust.notion.site/ODHack-Guidelines-Project-leads-June-2024-209fff76da8442d6a6a49ec9fb575af8)

#### Description:
The current documentation lacks information about the dependencies required for setting up a Soroban DApp. Additionally, it does not provide clear instructions on the necessary environment configurations and script executions.

#### Tasks:

1. **Update Documentation:**
   - Include a section detailing all dependencies required, specifically mentioning Docker.
   - Provide step-by-step instructions on how to install these dependencies.
   - user may change `contracts/config` to add a mainner (or public) RPC

2. **Script Execution Instructions:**
   - After running the `create-soroban-dapp` npx script, instruct users to execute `bash quickstart.sh standalone`.

3. **Environment Variables Configuration:**
   - Add instructions to configure `ADMIN_SECRET_KEY` and `MAINNET_RPC_URL` as per the `.env.example` file.

4. **Update preview_version.json:**
   - Ensure `preview_version.json` contains `"previewVersion": "21.0.1"`.
   - 
5. **Update quickstart.sh**
   - Update the `quickstart.sh` script to take both `.env` files into consideration when running.
   - expose port 3000. of soroban-preview image (to launch app on localhost:3000)

6. **Tutorial Creation:**
   - Create a tutorial for building the `esteblock/soroban-preview-docker` image (with version `21.0.1`).
   - Include instructions on running the image using the `quickstart.sh` script.

#### Acceptance Criteria:
- Users should be able to deploy a greeting contract to the testnet by following the updated documentation.

**Comment by petersdt** [comment]
@chopan123  can i be assigned to work Task 1: Update Documentation

**Comment by od-hunter** [comment]
Hi @chopan123 , can I be assigned this issue? This is my first time contributing to paltalaba ecosystem and I will love to be given the opportunity to proof my skills, thank you 🙏🏾

**Comment by Vaibhav0-1** [comment]
hey @chopan123  Can I be assigned to this issue?

**Comment by LamsyA** [comment]
Hi @chopan123,  I am blockchain developer with over two years working experience, I have read the instructions [here](https://github.com/paltalabs/create-soroban-dapp/issues/14#issue-2358482691) and gone through the repo. This is an issue I can handle easily. Kindly assign it to me.

**Comment by jedstroke** [comment]
GM @chopan123, here's my portfolio: https://www.jedshock.com/. I hope I am deemed fit enough to tackle on this issue?

**Comment by Naomi-Gift** [comment]
@chopan123 Can I be assigned this issue? I am a Web3 developer and also a documentarian, here is a link to my onlydust profile https://app.onlydust.com/u/Gift-Naomi.
I reviewed the task for updating the Soroban DApp documentation and am confident I can handle it. Here’s my approach:

1. Dependencies: Explicitly list Docker and provide installation instructions for Docker and Node.js.
2. Script Execution: Include instructions for running create-soroban-dapp and bash quickstart.sh standalone.
3. Environment Variables: Add steps to configure ADMIN_SECRET_KEY and MAINNET_RPC_URL in the .env file.
4. Tutorial: Create a guide for building and running the esteblock/soroban-preview-docker image.
And i will  let you know if you have any additional guidance or specific requirements.

Here are some documentation I’ve written https://hackmd.io/@xZ4BOZ5TTTy1I0ZQHXFOkg/SJRx_mkUA
https://hackmd.io/0AKb0F4sQbWQC4Imur3Zxg?view

**Comment by Vaibhav0-1** [comment]
hey @chopan123 Can I be assigned to this issue?

**Comment by mimiprosper** [comment]
Hi am a Frontend Dev, Smart Contract Dev and Technical Writer. Am currently studying Smart Contract Auditing. I have written articles: https://medium.com/@emma.onyedika.okeke

I have made successful documentation contribution for Starknet Scaffold in OD Hack project last month. I can do the same for you Sir. https://github.com/horuslabsio/Starknet-Scaffold/commits?author=mimiprosper

My Repo: https://github.com/mimiprosper

Thanks.

**Comment by mimiprosper** [comment]
Thanks for assigning me this task.
