### ISSUE TITLE
Update `stellar-sdk` package

### ISSUE THREAD

**Issue by chopan123** [paltalabs/create-soroban-dapp#15]
## ODHack
This issue is part of ODHack:

- [Description](https://app.onlydust.com/p/get-your-soroban-journey-started-with-create-soroban-dapp)
- [Guidelines](https://onlydust.notion.site/ODHack-Guidelines-Project-leads-June-2024-209fff76da8442d6a6a49ec9fb575af8)

### Description

`stellar-sdk` package is being deprecated and needs to be updated to the `@stellar/stellar-sdk` package.

**Comment by RajeshRk18** [comment]
Shall I take up this one?

**Comment by martinvibes** [comment]
I will like to work on this @chopan123

**Comment by Vaibhav0-1** [comment]
Shall I contribute to this project and update the deprecated package?

**Comment by nemealfaro** [comment]
Hi @chopan123 I would like to take this task. This would be my first issue on this project.
I would like help you and learn more about this

**Comment by Vaibhav0-1** [comment]
Hi team,

I'd like to take on the task of updating the stellar-sdk package to the new @stellar/stellar-sdk package. Here's my plan:

Update Package: Replace stellar-sdk with @stellar/stellar-sdk in package.json.
Adjust Imports: Update all import statements from stellar-sdk to @stellar/stellar-sdk.
Test: Ensure the application functions correctly with the new package by running all tests and verifying key functionalities.
Report Issues: Document and report any issues encountered during the update process.
Looking forward to your approval and assignment of this task.

vaibhav0-1([OnlyDust](https://app.onlydust.com/u/Vaibhav0-1) )

**Comment by PoulavBhowmick03** [comment]
Hello Project lead and maintainers, I am Poulav, a fullstack web3 developer. I have good grasp in MERN stack, Next.js, Typescript and other currently leading tech stacks in web. This is my first time contributing in this project but I feel I can work on this in great ease.
Here is my Profile:- https://app.onlydust.com/u/PoulavBhowmick03
Not much, since recently opened the account, but I can get this done since I have worked on similar issues before

# How I will handle this issue
> I will update all the currently present import statement of stellar sdk to @stellar/stellar-sdk
> Update it in the package.json and check whether the updated implementations pass the existing tests

I am highly interested to work on this issues, would be grateful if I were assigned with this task

**Comment by jsandinoDev** [comment]
Hi! @chopan123 My name is Josue Sandino. I'm a Software Engineer based in Costa Rica and this is my fisrt OD hack!

I'd love to have the opportunity to work on this issue, and be able to learn more about this project. 

My approach will be to replace the @stellar/stellar-sdk and then verify that the imports and test works fine.

**Comment by Vaibhav0-1** [comment]
Hi team,

I'm a FullStack Blockchain developer and proficient in MERN stack, Typescript.
 I'd like to take on the task of updating the stellar-sdk package to the new @stellar/stellar-sdk package. Here's my plan:

Update Package: Replace stellar-sdk with @stellar/stellar-sdk in package.json.
Adjust Imports: Update all import statements from stellar-sdk to @stellar/stellar-sdk.
Test: Ensure the application functions correctly with the new package by running all tests and verifying key functionalities.
Report Issues: Document and report any issues encountered during the update process.
Looking forward to your approval and assignment of this task.

vaibhav0-1([OnlyDust](https://app.onlydust.com/u/Vaibhav0-1) )

**Comment by armandocodecr** [comment]
# Request for Assignment: Update to `@stellar/stellar-sdk` Issue

Hello team,

My name is Armando, and I am interested in updating the `stellar-sdk` package as outlined in the ODHack issue. I have experience in managing dependencies and updating packages in various projects, and I believe I can effectively contribute to this task.

## Plan to Resolve the Issue

To update the `stellar-sdk` package from version `11.3.0` to the latest version of `@stellar/stellar-sdk`, I will follow a structured approach to ensure compatibility and functionality across the codebase. The latest version of `@stellar/stellar-sdk` as of now is `12.0.0`.

### Assess Current Usage

- I will review the current usage of `stellar-sdk` version `11.3.0` in the project to identify where and how it is being used. This includes:

  1. Imports and initializations of the `stellar-sdk` package.
  2. Methods and classes from the package that are utilized in the codebase.
  3. Any specific configurations or features used that might have been deprecated or modified in the latest version.

### Upgrade to `@stellar/stellar-sdk`

- I will update the package to the latest version, `12.0.0`, ensuring the new package `@stellar/stellar-sdk` is installed correctly by modifying the `package.json` and running the necessary package manager commands to update the dependencies.

### Code Refactoring and Compatibility

1. **Namespaces and Imports**: Update the import statements to reflect the new package name `@stellar/stellar-sdk`. The new package may have different import paths or require changes in how modules are accessed.
2. **Method and API Changes**: Identify changes in the APIs between `11.3.0` and `12.0.0`. This involves:
   - Updating method calls to match any new signatures or behaviors.
   - Refactoring any deprecated methods or properties that are no longer supported or have been replaced in the latest version.
   - Ensuring that any breaking changes in the library are addressed. For example, if there are changes in how transactions or networks are handled, these need to be reflected in the codebase.
3. **Configuration Updates**: Adjust any configuration settings or initialization logic that may have changed with the new version, including network settings or security protocols.

### Testing and Validation

- I will conduct thorough testing to ensure that all functionalities that depend on the `stellar-sdk` continue to work as expected with the new package. This includes:
  1. Running existing unit and integration tests to confirm that they pass with the updated SDK.
  2. Adding or modifying tests if there are new functionalities or changes in behavior.
  3. Manual testing of critical workflows that involve Stellar transactions or interactions to verify that there are no regressions.

### Documentation Update

- I will update any relevant documentation to reflect the changes made during the upgrade. This includes:
  1. Updating the README or other documentation files with new instructions if the setup or usage patterns of the SDK have changed.
  2. Providing migration notes if necessary, detailing any significant changes or new practices that should be followed after the update.

## Why This Solution is Optimal

1. **Comprehensive Upgrade Approach**: This approach ensures that all aspects of the code that interact with the `stellar-sdk` are thoroughly reviewed and updated, minimizing the risk of issues arising from the upgrade.
2. **Maintain Compatibility**: By focusing on compatibility and refactoring code to accommodate API changes, the solution ensures that the project remains functional and up-to-date with the latest improvements and security features of the SDK.
3. **Thorough Testing**: Emphasizing extensive testing guarantees that the updated SDK integrates smoothly into the existing codebase without introducing new bugs or regressions.

I am confident that this structured and meticulous approach will effectively address the requirements of the issue and ensure a smooth transition to the latest SDK version. I am available for further discussion to align on any specific expectations or adjustments needed.

Thank you for considering my request.

Best regards,  
Armando  
[My OnlyDust Profile](https://app.onlydust.com/u/armandocodecr)
