### ISSUE TITLE
Add support for HanaWallet and Lobstr

### ISSUE THREAD

**Issue by chopan123** [paltalabs/create-soroban-dapp#16]
## ODHack
This issue is part of ODHack:

- [Description](https://app.onlydust.com/p/get-your-soroban-journey-started-with-create-soroban-dapp)
- [Guidelines](https://onlydust.notion.site/ODHack-Guidelines-Project-leads-June-2024-209fff76da8442d6a6a49ec9fb575af8)

### Description

Soroban-react is now supporting HanaWallet and Lobstr. Add support for these wallets in the Soroban DApp.

**Comment by Ppixelbro** [comment]
Hi, I am interested in working on this issue to add support for HanaWallet and Lobstr. I plan to start by reviewing the current implementation of Soroban-react and understanding how wallet support is managed. Then, I will add the necessary support for HanaWallet and Lobstr and perform tests to ensure everything works correctly. Thank you!

**Comment by PedroCo3lho** [comment]
I'd like to work on this issue. I have checked the Soroban-react repository, and it seems straightforward to add HanaWallet and Lobstr support in the Soroban DApp.
I have previous experience integrating wallets into DApps across different blockchains, which involves similar steps. I'd love to contribute to this project.

Can I be assigned to this task?
Thanks!

**Comment by jedstroke** [comment]
GM @chopan123, here's my portfolio: https://www.jedshock.com/. I hope I am deemed fit enough to tackle on this issue?
