### ISSUE TITLE
Handle missing contract

### ISSUE THREAD

**Issue by chopan123** [paltalabs/create-soroban-dapp#17]
## ODHack
This issue is part of ODHack:

- [Description](https://app.onlydust.com/p/get-your-soroban-journey-started-with-create-soroban-dapp)
- [Guidelines](https://onlydust.notion.site/ODHack-Guidelines-Project-leads-June-2024-209fff76da8442d6a6a49ec9fb575af8)

### Description

Make a warning when there is no contract deployed. Currently it just saying that there was an error while searching the contract, not specifying that the contract is missing.

### Expected Behaviour
When in standalone, there will not be a contract deployed, then it should say that we need to deploy a contract first.

**Comment by od-hunter** [comment]
Hello @chopan123 , I’m waiting to be assigned by you please. The approach I intend taking in solving this issue is first, I’ll update the error handling logic to specifically check if the error is due to a missing contract, If the error is due to a missing contract, I’ll change the error message( that is I’ll modify the error message to clearly state that the contract is not deployed). I’ll ensure the warning advises that a contract needs to be deployed first, then I’ll  Implement the check and message in the contract search logic.

Can I be assigned this issue please?

**Comment by Vaibhav0-1** [comment]
Hey @chopan123 Can you assign this issue to me as I've mentioned the changes needed to resolve this issue,

Issue Resolution Proposal

Changes Proposed:
Update isContractDeployed to return false in standalone mode when checking for deployed contracts.
Modify contractTxWithToast to display a specific toast error when no contract is deployed in standalone mode.

Implementation Plan:
Adjust isContractDeployed to recognize standalone mode and return false appropriately.
Enhance contractTxWithToast to trigger a toast error message when attempting transactions without a deployed contract in standalone mode.

Next Steps:
Implement proposed changes in isContractDeployed and contractTxWithToast.
Test thoroughly to confirm the effectiveness of new contract deployment warnings.

**Comment by Naomi-Gift** [comment]
@chopan123 can I be assigned this issue?
I’m a Web3 developer I have the experience , I can tackle this issue
Here is a my onlydust profile https://app.onlydust.com/contributions?tab=COMPLETED

**Comment by Vaibhav0-1** [comment]
Hey @chopan123 Can you assign this issue to me as I've mentioned the changes needed to resolve this issue,

Issue Resolution Proposal

Changes Proposed:
Update isContractDeployed to return false in standalone mode when checking for deployed contracts.
Modify contractTxWithToast to display a specific toast error when no contract is deployed in standalone mode.

Implementation Plan:
Adjust isContractDeployed to recognize standalone mode and return false appropriately.
Enhance contractTxWithToast to trigger a toast error message when attempting transactions without a deployed contract in standalone mode.

Next Steps:
Implement proposed changes in isContractDeployed and contractTxWithToast.
Test thoroughly to confirm the effectiveness of new contract deployment warnings.

**Comment by fishseabowl** [comment]
Could I take this? Thanks
