### ISSUE TITLE
Create TS tests

### ISSUE THREAD

**Issue by chopan123** [paltalabs/create-soroban-dapp#19]
## ODHack
This issue is part of ODHack:

- [Description](https://app.onlydust.com/p/get-your-soroban-journey-started-with-create-soroban-dapp)
- [Guidelines](https://onlydust.notion.site/ODHack-Guidelines-Project-leads-June-2024-209fff76da8442d6a6a49ec9fb575af8)

### Description

We can test the contracts by using rust tests. However we find useful to create some tests in typescript to test the contracts deployed on a network. 

Create a test, that will test the deployment of greeting contract deployed on the network. We encourage to use `chai` library.

**Comment by zintarh** [comment]
Hi @chopan123 I would like to work on this

**Comment by Dprof-in-tech** [comment]
Hello @chopan123 
I'm Isaac, a full stack JavaScript developer with a history of successful contributions to starknet and OnlyDust projects.

I would love to be assigned to this issue so I can write these tests. Though this would be my first time writing test files using the chai library , I have experience with writing unit tests as can be confirmed from my GitHub profile at https://github.com/dprof-in-tech and this would be an opportunity to learn.

Below is my OnlyDust profile and I would wait on your response

https://app.onlydust.com/u/Dprof-in-tech

Thanks

**Comment by BraCR10** [comment]
Hi @chopan123 I’m Brian, I’d like to work on this issue. I have used mocha and chai to do some testing in JS, I have also been using TS in other projects. I would love to take the test and learn in the process.

**Comment by jedstroke** [comment]
GM @chopan123, here's my portfolio: https://www.jedshock.com/. I hope I am deemed fit enough to tackle on this issue?

**Comment by Dprof-in-tech** [comment]
Good day @chopan123 

Please can this issue be solely assigned to @BraCR10 
I have my hands full at them moment and can't sync with him as expected, he's doing a very nice job by the way
Thank you

**Comment by Ppixelbro** [comment]
Hi, I would like to offer my support to @BraCR10 in resolving this issue now that @Dprof-in-tech is no longer available. If assigned, I will make sure to get in touch with @BraCR10 to coordinate our efforts and ensure that the TypeScript tests using the Chai library are completed effectively.

Please let me know how I can assist and work together with @BraCR10 to make progress on this task.

Thank you for your attention and support.

**Comment by BraCR10** [comment]
Greeting contract test using TS, chai and mocha #29
