### ISSUE TITLE
Deploy a new instance of greeting contract!

### ISSUE THREAD

**Issue by chopan123** [paltalabs/create-soroban-dapp#20]
## ODHack
This issue is part of ODHack:

- [Description](https://app.onlydust.com/p/get-your-soroban-journey-started-with-create-soroban-dapp)
- [Guidelines](https://onlydust.notion.site/ODHack-Guidelines-Project-leads-June-2024-209fff76da8442d6a6a49ec9fb575af8)

### Description
After the recent reset of Testnet, we need to deploy a new instance of the greeting and tweaked_greeting contract. Take advantage of Soroban 21!
Update `deployments.json` file with the new contract address.

Report any issue that make this journey not smooth (after some fixes have been done).

### Note
Today (June 17th) is not trivial to use this repo due to the recent changes of dependencies. So, you might want to tackle other issues first.

**Comment by DevPelz** [comment]
Hello @chopan123 can i work on this? I can deploy a new instance of the two contracts and include their addresses in the .json file when it is ready to go.

**Comment by Vaibhav0-1** [comment]
Hey @chopan123 I would like to contribute to this project by deploying a new instance and including their addresses in the .json file #ODHack

**Comment by od-hunter** [comment]
Hi @chopan123  , can I be assigned this issue? This is my first time contributing to paltalaba ecosystem and I will love to be given the opportunity to proof my skills, thank you 🙏🏾

**Comment by Vaibhav0-1** [comment]
Hi team,

I'd like to take on the task of deploying new instances of the "greeting" and "tweaked_greeting" contracts following the recent reset of Testnet. Here's my plan:

1. **Set Up Environment**: Ensure all dependencies are installed and the latest changes are pulled.
2. **Deploy Contracts**: Use the Soroban CLI to deploy the "greeting" and "tweaked_greeting" contracts to the testnet.
3. **Update `deployments.json`**: Add the new contract addresses to the `deployments.json` file.
4. **Report Issues**: Document and report any issues encountered during the process.

Looking forward to your approval and assignment of this task.

Vaibhav0-1([onlyDust](https://app.onlydust.com/u/Vaibhav0-1))

**Comment by jedstroke** [comment]
GM @chopan123, here's my portfolio: https://www.jedshock.com/. I hope I am deemed fit enough to tackle on this issue?

**Comment by Vaibhav0-1** [comment]
Hi team,

I'd like to take on the task of deploying new instances of the "greeting" and "tweaked_greeting" contracts following the recent reset of Testnet. Here's my plan:

Set Up Environment: Ensure all dependencies are installed and the latest changes are pulled.
Deploy Contracts: Use the Soroban CLI to deploy the "greeting" and "tweaked_greeting" contracts to the testnet.
Update deployments.json: Add the new contract addresses to the deployments.json file.
Report Issues: Document and report any issues encountered during the process.
Looking forward to your approval and assignment of this task.

Vaibhav0-1([onlyDust](https://app.onlydust.com/u/Vaibhav0-1))

**Comment by chopan123** [comment]
I won't assign this yet

**Comment by KoxyG** [comment]
Pls assign me to this

**Comment by DevPelz** [comment]
> I won't assign this yet

why? is there any further developments we have to wait for first or due to some other reasons?

**Comment by josephchimebuka** [comment]
Hello @chopan123, I hope this message finds you well. I am writing to express my interest in tackling this issue.  I am Joseph Chimebuka and I have been contributing to projects on onlydust for the past few months now.  I am confident in my ability to effectively address and resolve this issue. Here's how I will solve the issue


I will deploy new instances of the greeting and tweaked_greeting contracts on Testnet using Soroban 21, update the deployments.json file with the new contract addresses, and document any encountered issues.
