### ISSUE TITLE
`airdropAccount` should also support standalone

### ISSUE THREAD

**Issue by chopan123** [paltalabs/create-soroban-dapp#21]
## ODHack
This issue is part of ODHack:

- [Description](https://app.onlydust.com/p/get-your-soroban-journey-started-with-create-soroban-dapp)
- [Guidelines](https://onlydust.notion.site/ODHack-Guidelines-Project-leads-June-2024-209fff76da8442d6a6a49ec9fb575af8)

### Description
`airdropAccount` function should receive a `network` parameter to support standalone network. When no network is passed, it should use `testnet` as default.

**Comment by No-bodyq** [comment]
Is this open for contribution rn??
If so can I get assigned??
As the description suggests I will modify the function to accept a `network` parameter whilst keeping the default as testnet in the case no network is selected whilst ensuring appropriate corroboration of said parameter

**Comment by od-hunter** [comment]
Hi @chopan123 , can I be assigned this issue? This is my first time contributing to paltalaba ecosystem and I will love to be given the opportunity to proof my skills. 
To solve this issue, I’ll modify the ‘airdropAccount’ function to include an optional `network` parameter and if no network is provided, I’ll set the default to ‘testnet’, then I’ll update the function logic to handle different networks based on this parameter. I’ll also Ensure proper handling and validation of the network parameter within the function. Kindly assign me so I can begin work, thank you.

**Comment by Bosun-Josh121** [comment]
Hello, I have a software engineering background but new here and looking to make my first contribution. I can tackle this within today if assigned

**Comment by acquaahj-dev** [comment]
Hello,
I recently got introduced to OnlyDust at muAccra and I would love to contribute to this project if given the opportunity.

**Comment by HumbertoTM10** [comment]
Hi @chopan123, is this still available to work on it?

**Comment by jedstroke** [comment]
GM @chopan123, here's my portfolio: https://www.jedshock.com. I hope I am deemed fit enough to tackle on this issue?

**Comment by bitfalt** [comment]
Hi! My name is Daniel and I'm a Computer Science student. This is my first ODHack and I would love to contribute to this project and tackle the issue.

I would solve this issue in the following way:
1. Read and understand the code of the function `airdropAcount`
2. Implement the network parameter
3. Make the validation that if none is passed, it default to the `testnet`
4. Additionally, test the implementation to ensure the behavior is the expected one.

If I have any questions regarding the code, I would ask one of the project leads for guidance.

**Comment by bitfalt** [comment]
I have my approach planned already, however I would like some feedback from @chopan123 

### Approach
- Navigating through the code, I understand that the network configuration is loaded from a file. The function, config, which is in charge of loading the necessary configuration by using `Env.Config.loadFromFile` is locate in `soroban-react-dapp/contracts/util/env.config.ts` (Also while looking in `soroban-react-dapp/contracts/util/contract.ts` the import of `config` is defined as `env.config.js`, probably this doesn't matter, but just pointing it out).
- `loadFromFile` receives a string which is the network parameter, so I assume the new behaviour of `airdropAccount` would be the following
	1. Modify the function to receive a network parameter which could be a `string` or `undefined`
	2. Validate that `network_param == standalone`, if it is we would run `conf = config(network_param)` otherwise `conf = config(testnet)` (have in mind that wouldn't be the name of the variable nor the parameter, these are placeholders for the explanation). I was wondering what would be the difference between `testnet` and `testnet-public`, since in the `configs.json` file they are defined the same.
	3. Once the proper configuration is setup, we would run the function normally as it is right now. So this means `await conf.rpc.requestAidrop(…, conf.friendbot)
`

This would be the approach that I thought of and would be taking. **Any feedback or question regarding my approach is well apreciated!**
