### ISSUE TITLE
[D1.2] Boilerplate - Front-end integration and styling

### ISSUE THREAD

**Issue by benjaminsalon** [paltalabs/create-soroban-dapp#3]
We want our boilerplate to look like something nice and user friendly UI.
Objective: Defining functionalities, good UI and beautiful style

**Comment by esteblock** [comment]
- [x] What our boilerplate will do? Set a title?
- [x] How this will be shown in the frontend?
- [x] What other info the frontend will show? (Network, passphrase, RPC, wallet address, etc...)
- [x] Make the fronted beautiful
