### ISSUE TITLE
improve documentation Manual Cloning or NPX

### ISSUE THREAD

**Issue by esteblock** [paltalabs/create-soroban-dapp#37]
Its not clear for users.. they are confused

- [ ] Explain that you have multiple ways to start playing around with the repo
- [ ] Update docs also on docs/ folder to deploy it on gitbook
- [ ] change troubleshoot reference to devs@paltalabs.io (@esteblock may you check this address is correct?)
- [ ] Follow docs from scratch to make sure everything is ok

**Comment by fishonamos** [comment]
Let me quickly raise a pr to close this @esteblock

**Comment by Naomi-Gift** [comment]
@esteblock Can i work on this when there is more clarification on the issue?
I have written documentations on this repo before and they have all been merged.
