### ISSUE TITLE
[D1.1] Boilerplate - Initial Boilerplate Framework Setup

### ISSUE THREAD

**Issue by benjaminsalon** [paltalabs/create-soroban-dapp#5]
This first task if for setting the initial structure of the dapp that we want:

- Which framework ? (Nextjs)
- Make it a create-soroban-dapp npx script:

This will be the basis on all work on the BoilerPlate.

**Comment by esteblock** [comment]
Publish: npx create-soroban-dapp
Document in README: How to "build", how to publish new versions, etc...
